version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    env_file:
      - ../apps/backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    command: ["npm", "run", "start:prod"]

volumes:
  postgres_data:
