services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    profiles: ["local", "staging", "prod"]

  # Backend Application (only for staging/prod)
  backend:
    build:
      context: ..
      dockerfile: apps/backend/Dockerfile
    env_file:
      - .env.${ENV}
    ports:
      - "${BACKEND_PORT}:3001"
    depends_on:
      - postgres
    command: ["node", "dist/main.js"]
    restart: unless-stopped
    profiles: ["staging", "prod"]

  # Caddy Reverse Proxy (only for staging/prod)
  caddy:
    image: caddy:2
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./Caddyfile.${ENV}:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
    restart: unless-stopped
    profiles: ["staging", "prod"]

volumes:
  postgres_data:
  caddy_data:
  caddy_config: