services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_pwd
      POSTGRES_DB: biplace_prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: apps/backend/Dockerfile
    env_file:
      - ../apps/backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    command: ["node", "dist/main.js"]

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile-prod:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
