export const RESERVATION_WISH_REPOSITORY = Symbol('VALIDATION_ENGINE_RESERVATION_WISH_REPOSITORY');
export const PACK_REPOSITORY = Symbol('VALIDATION_ENGINE_PACK_REPOSITORY');
export const RESERVATION_REPOSITORY = Symbol('VALIDATION_ENGINE_RESERVATION_REPOSITORY');
