export const RESERVATION_WISH_REPOSITORY = Symbol('RESERVATION_WISH_REPOSITORY');
export const RESERVATION_REPOSITORY = Symbol('RESERVATION_REPOSITORY');
export const RESERVATION_WISH_NOTIFICATION_PORT = Symbol('RESERVATION_WISH_NOTIFICATION_PORT');
